# Generated by Django 5.1.4 on 2025-01-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default='123456789', max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.CharField(default='correo@gmail.com', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Usuario')], default=2),
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='username', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
