# Generated by Django 5.1.4 on 2025-01-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_usuario_contraseña_usuario_correo_usuario_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default='correo@gmail.com', max_length=100, unique=True),
        ),
    ]
