# Generated by Django 5.1.4 on 2025-01-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_usuario_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fotoperfil',
            field=models.ImageField(default='img/default.png', upload_to='fotoperfil'),
        ),
    ]
