# Generated by Django 5.1.4 on 2025-01-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_usuario_fotoperfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Producto', max_length=100)),
                ('descripcion', models.CharField(default='Descripcion', max_length=400)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('cantidad', models.IntegerField(default=0)),
                ('imagen1', models.CharField(default='img/default.png', max_length=100)),
                ('imagen2', models.CharField(default='img/default.png', max_length=100)),
                ('imagen3', models.CharField(default='img/default.png', max_length=100)),
                ('imagen4', models.CharField(default='img/default.png', max_length=100)),
                ('imagen5', models.CharField(default='img/default.png', max_length=100)),
                ('Especificaciones', models.CharField(default='Especificaciones', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fotoperfil',
            field=models.CharField(default='img/default.png', max_length=100),
        ),
    ]
