# Generated by Django 5.1.4 on 2025-01-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_producto_alter_usuario_fotoperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen1',
            field=models.ImageField(default='img/default_P.png', upload_to='img/Img_Productos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen2',
            field=models.ImageField(default='img/default_P.png', upload_to='img/Img_Productos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen3',
            field=models.ImageField(default='img/default_P.png', upload_to='img/Img_Productos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen4',
            field=models.ImageField(default='img/default_P.png', upload_to='img/Img_Productos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen5',
            field=models.ImageField(default='img/default_P.png', upload_to='img/Img_Productos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fotoperfil',
            field=models.ImageField(default='img/default.png', upload_to='img/Img_Usuarios'),
        ),
    ]
