# Generated by Django 5.1.4 on 2025-01-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_producto_imagen1_alter_producto_imagen2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Especificaciones',
            new_name='especificaciones',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen1',
            field=models.ImageField(blank=True, default='img/img_p/default_P.png', null=True, upload_to='uploads/'),
        ),
    ]
