# Generated by Django 5.1.4 on 2025-01-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_alter_usuario_contraseña_alter_usuario_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default='123456789', max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default='correo@gmail.com', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='username', max_length=50, unique=True),
        ),
    ]
