# Generated by Django 5.1.4 on 2025-01-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_alter_usuario_contraseña_alter_usuario_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fotoperfil',
            field=models.ImageField(default='uploads/avatars/default_A.svg', upload_to='uploads/avatars/'),
        ),
    ]
