# Generated by Django 5.1.4 on 2025-01-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0021_remove_usuario_rol_usuario_biografia_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
