# Generated by Django 5.1.4 on 2025-01-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0024_carrito_productos_alter_carrito_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(default='uploads/avatars/default_A.svg', upload_to='uploads/avatars/'),
        ),
    ]
